spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: pgadmin
    password: pgpwd
  jpa:
    show-sql: true
    generate-ddl: true
  data:
    mongodb:
      database: links
      host: localhost
      port: 27017
#      uri: mongodb://localhost:27017/links
