version: '3'
services:
  db-postgres:
    image: 'postgres'
    container_name: 'postgres'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgpwd

  db-mongo:
    image: 'mongo'
    container_name: 'mongo'
    ports:
      - '27017:27017'

  tool-mongo-express:
    image: 'mongo-express'
    container_name: 'mongo-express'
    ports:
      - '8081:8081'
